
import React, { useState, useMemo } from 'react';
import { Project, Lookups, Language } from '../types';
import SearchableSelect from './SearchableSelect';

interface AddProjectModalProps {
  lookups: Lookups;
  onClose: () => void;
  onAddProject: (newProject: Omit<Project, 'id' | 'projectCode' | 'country' | 'category' | 'team' | 'product' | 'status' | 'projectManager' | 'customer'>) => Promise<void>;
  language: Language;
}

const AddProjectModal: React.FC<AddProjectModalProps> = ({ lookups, onClose, onAddProject, language }) => {
  const [formData, setFormData] = useState({
      name: '',
      description: '',
      countryId: '',
      categoryId: '',
      teamId: '',
      productId: '',
      statusId: '',
      projectManagerId: '',
      customerId: '',
      launchDate: '',
      actualStartDate: '',
      expectedClosureDate: '',
      progress: 0,
      revenueImpact: 1,
      strategicValue: 1,
      deliveryRisk: 1,
      customerPressure: 1,
      resourceLoad: 1,
  });

  const [isSubmitting, setIsSubmitting] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [isSuccess, setIsSuccess] = useState(false);
  
  const translations = {
      ar: {
          title: "إضافة مشروع جديد",
          projectName: "اسم المشروع",
          projectCode: "الكود",
          autoGenerated: "تلقائي",
          description: "الوصف",
          country: "الدولة",
          category: "الفئة",
          team: "الفريق",
          product: "المنتج",
          status: "الحالة",
          projectManager: "مدير المشروع",
          customer: "العميل",
          launchDate: "الإطلاق",
          actualStartDate: "البدء الفعلي",
          expectedClosureDate: "الإغلاق المتوقع",
          progress: "التقدم",
          weightTitle: "الأوزان (1-5)",
          revenueImpact: "الإيرادات",
          strategicValue: "الاستراتيجية",
          deliveryRisk: "المخاطر",
          customerPressure: "الضغط",
          resourceLoad: "الموارد",
          add: "إضافة",
          cancel: "إلغاء",
          selectHere: "اختر...",
          searchCustomers: "بحث...",
          searchCountries: "بحث...",
          submitting: "حفظ...",
          successMsg: "تمت الإضافة!",
          errorPrefix: "خطأ: "
      },
      en: {
          title: "New Project",
          projectName: "Project Name",
          projectCode: "Code",
          autoGenerated: "Auto",
          description: "Description",
          country: "Country",
          category: "Category",
          team: "Team",
          product: "Product",
          status: "Status",
          projectManager: "Manager",
          customer: "Customer",
          launchDate: "Launch",
          actualStartDate: "Actual Start",
          expectedClosureDate: "Expected Closure",
          progress: "Progress",
          weightTitle: "Weights (1–5)",
          revenueImpact: "Revenue",
          strategicValue: "Strategic",
          deliveryRisk: "Risk",
          customerPressure: "Pressure",
          resourceLoad: "Resources",
          add: "Add Project",
          cancel: "Cancel",
          selectHere: "Select...",
          searchCustomers: "Search...",
          searchCountries: "Search...",
          submitting: "Saving...",
          successMsg: "Added!",
          errorPrefix: "Error: "
      },
  };
  const t = translations[language];

  const customerOptions = useMemo(() => 
    lookups.customers.map(c => ({ value: c.id, label: c.name })),
    [lookups.customers]
  );

  const countryOptions = useMemo(() => 
    [...lookups.countries]
        .map(c => ({ value: c.id, label: c.name }))
        .sort((a, b) => a.label.localeCompare(b.label, language === 'ar' ? 'ar' : 'en')),
    [lookups.countries, language]
  );

  const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>) => {
      const { name, value } = e.target;
      setFormData(prev => ({...prev, [name]: value}));
  };

  const handleCustomerChange = (val: string) => {
    setFormData(prev => ({ ...prev, customerId: val }));
  };

  const handleCountryChange = (val: string) => {
    setFormData(prev => ({ ...prev, countryId: val }));
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!formData.name || !formData.customerId) return;
    
    setError(null);
    setIsSubmitting(true);

    try {
        const submissionData = {
            ...formData,
            launchDate: formData.launchDate || null,
            actualStartDate: formData.actualStartDate || null,
            expectedClosureDate: formData.expectedClosureDate || null,
            progress: Number(formData.progress),
            revenueImpact: Number(formData.revenueImpact),
            strategicValue: Number(formData.strategicValue),
            deliveryRisk: Number(formData.deliveryRisk),
            customerPressure: Number(formData.customerPressure),
            resourceLoad: Number(formData.resourceLoad),
        };

        await onAddProject(submissionData);
        setIsSuccess(true);
        setTimeout(() => {
            onClose();
        }, 1500);
    } catch (err: any) {
        setError(t.errorPrefix + (err.message || "Connection failed"));
    } finally {
        setIsSubmitting(false);
    }
  };
  
  const inputClasses = "w-full p-2 bg-slate-50 dark:bg-slate-800/50 rounded-lg border border-slate-200 dark:border-slate-700 focus:outline-none focus:ring-1 focus:ring-violet-500 text-slate-800 dark:text-white text-xs";
  const selectClasses = "w-full p-2 bg-slate-50 dark:bg-slate-800/50 rounded-lg border border-slate-200 dark:border-slate-700 focus:outline-none focus:ring-1 focus:ring-violet-500 text-slate-800 dark:text-white text-xs";

  const WeightSelect = ({ label, name, value }: { label: string, name: string, value: number }) => (
      <div className="flex-1 min-w-0">
          <label className="block text-[9px] font-bold text-slate-500 mb-1 truncate uppercase">{label}</label>
          <select name={name} value={value} onChange={handleChange} className={selectClasses} disabled={isSubmitting}>
              {[1, 2, 3, 4, 5].map(v => <option key={v} value={v}>{v}</option>)}
          </select>
      </div>
  );

  return (
    <div className="fixed inset-0 bg-slate-900/80 backdrop-blur-sm flex items-center justify-center z-[100] p-4">
      <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-3xl shadow-2xl w-full max-w-3xl overflow-hidden" dir={language === 'ar' ? 'rtl' : 'ltr'}>
        <div className="p-5 flex justify-between items-center border-b border-slate-100 dark:border-slate-800">
            <h2 className="text-lg font-black text-slate-800 dark:text-white uppercase tracking-tight">{t.title}</h2>
            <button onClick={onClose} disabled={isSubmitting} className="text-slate-400 hover:text-slate-600 text-2xl font-bold transition-colors">&times;</button>
        </div>

        <div className="p-5 space-y-4">
            {error && <div className="p-2.5 text-[10px] font-bold text-red-600 bg-red-50 rounded-xl">{error}</div>}
            {isSuccess && <div className="p-2.5 text-[10px] font-bold text-emerald-600 bg-emerald-50 rounded-xl">{t.successMsg}</div>}

            <form onSubmit={handleSubmit} className="space-y-4">
              <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
                  <div className="md:col-span-3">
                    <label className="block text-[10px] font-black text-slate-400 uppercase mb-1">{t.projectName}</label>
                    <input type="text" name="name" value={formData.name} onChange={handleChange} required disabled={isSubmitting} className={inputClasses}/>
                  </div>
                  <div>
                    <label className="block text-[10px] font-black text-slate-400 uppercase mb-1">{t.projectCode}</label>
                    <input type="text" placeholder={t.autoGenerated} disabled className={`${inputClasses} opacity-50 italic`}/>
                  </div>
              </div>

              <div>
                  <label className="block text-[10px] font-black text-slate-400 uppercase mb-1">{t.description}</label>
                  <input type="text" name="description" value={formData.description} onChange={handleChange} disabled={isSubmitting} className={inputClasses}/>
              </div>
              
              <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
                  <div>
                      <label className="block text-[10px] font-black text-slate-400 uppercase mb-1">{t.customer}</label>
                      <SearchableSelect options={customerOptions} value={formData.customerId} onChange={handleCustomerChange} placeholder={t.selectHere} searchPlaceholder={t.searchCustomers} language={language} />
                  </div>
                  <div>
                      <label className="block text-[10px] font-black text-slate-400 uppercase mb-1">{t.country}</label>
                      <SearchableSelect options={countryOptions} value={formData.countryId} onChange={handleCountryChange} placeholder={t.selectHere} searchPlaceholder={t.searchCountries} language={language} />
                  </div>
                  <div>
                      <label className="block text-[10px] font-black text-slate-400 uppercase mb-1">{t.projectManager}</label>
                      <select name="projectManagerId" value={formData.projectManagerId} onChange={handleChange} required disabled={isSubmitting} className={selectClasses}>
                          <option value="" disabled>{t.selectHere}</option>
                          {lookups.projectManagers.map(l => (<option key={l.id} value={l.id}>{l.name}</option>))}
                      </select>
                  </div>
                   <div>
                      <label className="block text-[10px] font-black text-slate-400 uppercase mb-1">{t.status}</label>
                      <select name="statusId" value={formData.statusId} onChange={handleChange} required disabled={isSubmitting} className={selectClasses}>
                          <option value="" disabled>{t.selectHere}</option>
                          {lookups.projectStatuses.map(l => (<option key={l.id} value={l.id}>{l.name}</option>))}
                      </select>
                  </div>
              </div>

              {/* Weighting Section - Compact */}
              <div className="p-4 bg-slate-50 dark:bg-slate-800/30 rounded-2xl border border-slate-100 dark:border-slate-800">
                  <h3 className="text-[9px] font-black text-violet-500 uppercase mb-3 tracking-widest">{t.weightTitle}</h3>
                  <div className="flex flex-wrap md:flex-nowrap gap-3">
                      <WeightSelect label={t.revenueImpact} name="revenueImpact" value={formData.revenueImpact} />
                      <WeightSelect label={t.strategicValue} name="strategicValue" value={formData.strategicValue} />
                      <WeightSelect label={t.deliveryRisk} name="deliveryRisk" value={formData.deliveryRisk} />
                      <WeightSelect label={t.customerPressure} name="customerPressure" value={formData.customerPressure} />
                      <WeightSelect label={t.resourceLoad} name="resourceLoad" value={formData.resourceLoad} />
                  </div>
              </div>

              <div className="grid grid-cols-3 gap-4">
                  <div>
                      <label className="block text-[10px] font-black text-slate-400 uppercase mb-1">{t.launchDate}</label>
                      <input type="date" name="launchDate" value={formData.launchDate} onChange={handleChange} disabled={isSubmitting} className={inputClasses}/>
                  </div>
                  <div>
                      <label className="block text-[10px] font-black text-slate-400 uppercase mb-1">{t.actualStartDate}</label>
                      <input type="date" name="actualStartDate" value={formData.actualStartDate} onChange={handleChange} disabled={isSubmitting} className={inputClasses}/>
                  </div>
                  <div>
                      <label className="block text-[10px] font-black text-slate-400 uppercase mb-1">{t.expectedClosureDate}</label>
                      <input type="date" name="expectedClosureDate" value={formData.expectedClosureDate} onChange={handleChange} disabled={isSubmitting} className={inputClasses}/>
                  </div>
              </div>

              <div className="flex items-center gap-4">
                  <div className="flex-1">
                    <label className="block text-[10px] font-black text-slate-400 uppercase mb-1">{t.progress} ({formData.progress}%)</label>
                    <input type="range" name="progress" min="0" max="100" value={formData.progress} onChange={handleChange} disabled={isSubmitting} className="w-full h-1.5 bg-slate-200 rounded-lg appearance-none cursor-pointer accent-violet-600"/>
                  </div>
              </div>

              <div className="flex justify-end gap-3 pt-4 border-t border-slate-100 dark:border-slate-800">
                  <button type="button" onClick={onClose} disabled={isSubmitting} className="px-6 py-2 text-[10px] font-black text-slate-400 uppercase tracking-widest">{t.cancel}</button>
                  <button type="submit" disabled={isSubmitting || isSuccess} className="px-10 py-2.5 bg-violet-600 text-white rounded-xl text-[10px] font-black uppercase tracking-widest hover:bg-violet-700 shadow-lg shadow-violet-500/20 flex items-center gap-2">
                    {isSubmitting && <span className="w-3 h-3 border-2 border-white/30 border-t-white rounded-full animate-spin"></span>}
                    {isSuccess ? t.successMsg : (isSubmitting ? t.submitting : t.add)}
                  </button>
              </div>
            </form>
        </div>
      </div>
    </div>
  );
};

export default AddProjectModal;
